### PR TITLE
Cleanup of the code, implemeting Write

### PR DESCRIPTION
**Pull request by Sniper10754**
this pull request contains a second part of the refactor, and the implementation of `std::fmt::Write` for `Console`, to allow writing without necessary overhead.

### CODE REVIEW

**Comment by Eyesonjune18** [comment]
Considering that the canonical way to write to the console is by using `writeln!()`, you can simply make the print methods private and remove your query comment.

**Comment by Sniper10754** [comment]
ok

**Comment by Sniper10754** [comment]
at this point we could remove `Console::println` method since it's no longer used.

**Comment by hahohihu** [comment]
Here are macros to write to console without the unwrap, for consideration. I think `unwrap` should be alarming, and considering how common printing to console will be, I think it'd be sensible to hide it when we're sure it can't happen.
```rs
/// For macro use
pub fn _is_console(_: &mut Console<'_>) {}

#[macro_export]
macro_rules! show {
    ($dst:expr, $($arg:tt)*) => {{
        let console = $dst;
        $crate::console::_is_console(console);
        // console cannot fail writing
        console.write_fmt(::std::format_args!($($arg)*)).unwrap()
    }};
}

#[macro_export]
macro_rules! showln {
    ($dst:expr $(,)?) => {
        $crate::show!($dst, "\n")
    };
    ($dst:expr, $($arg:tt)*) => {{
        let console = $dst;
        $crate::_is_console(console);
        // console cannot fail writing
        console.write_fmt($crate::format_args_nl!($($arg)*)).unwrap()
    }};
}
```

**Comment by Eyesonjune18** [comment]
Are we sure that this is better than just having macros that use the original `.println()` and `.print()` methods? They do not require any implicit unwrapping. Also, then we could just infer that the name of the console is always `console` to reduce boilerplate. (Inside `rush_state::console` we would have to continue using `self.print()` and `self.println()`)

**Comment by hahohihu** [comment]
There are two separate points there:
> Are we sure that this is better than just having macros that use the original .println() and .print() methods? They do not require any implicit unwrapping.
It's an implementation detail either way - I do think we should have some sort of first-class macro as our API, but we can use the original `println`/`print` functions or `Write` or anything else. One issue with the original `print` functions is that they have an intermediate string allocation, which is slightly wasteful, but we can ignore that and use them for now.

> Also, then we could just infer that the name of the console is always console to reduce boilerplate.
I'm a bit mixed on this - it'd be more concise, but having had massive headaches from unsanitary macros in the past, I'm not sure it'd be a good idea. It'll save us typing, but probably give newcomers a mild headache if they happen to do something differently.

**Pull request closed without merging**
